### ISSUE TITLE
Error in Supervisor Core after update to 4.9

### ISSUE THREAD

**Issue by gbuico** [Cyr-ius/hass-heatzy#14]
Hi
After the update to 4.9 I find error messages during startup
Her is what I get:
2021-12-22 10:25:54 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform heatzy.switch: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).

In the log I find the following entries:
Logger: homeassistant.setup
Source: setup.py:316
First occurred: 10:25:54 (1 occurrences)
Last logged: 10:25:54
Unable to prepare setup for platform heatzy.switch: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:269
Integration: Sensor (documentation, issues)
First occurred: 10:25:22 (1 occurrences)
Last logged: 10:25:22
sensor.dhwp_actuator_middle_water_temperature has unknown unit None

Apparently the device is reacting to the commands, even if with a big delay.
I already tried to remove and reinstall the integration

I'm using an Heatzy Pilote connected to an Acova radiator

Any suggestion?

**Comment by gbuico** [comment]
Solved by updating Ha Core to 2021.12.6
